version: '3'
services:
  app:
    build: .
    restart: always
    networks:
      - app
    ports:
      - "8080:8080"
    depends_on:
      - db
  db:
    container_name: database
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: $DB_USERNAME
      POSTGRES_PASSWORD: $DB_PASSWORD
      POSTGRES_DB: $DB_NAME
      POSTGRES_DATA: /data/postgres
    networks:
      - app
    volumes:
      - db:/data/postgres
    ports:
      - "5432:5432"

volumes:
  db:
    driver: local
networks:
  app: